# =============================================================================
#  GMI Quality Management System – Cloud Build CI/CD
#  Triggered automatically on push to main branch.
# =============================================================================

substitutions:
  _REGION:      europe-west1
  _SERVICE:     gmi-qms
  _DB_INSTANCE: gmi-qms-db
  _DOMAIN:      qms.gmiberia.com

steps:
  # ── 1. Build Docker image ──────────────────────────────────────────────────
  - name: gcr.io/cloud-builders/docker
    id: build
    args:
      - build
      - --platform=linux/amd64
      - --tag=europe-west1-docker.pkg.dev/$PROJECT_ID/gmi/qms-backend:$COMMIT_SHA
      - --tag=europe-west1-docker.pkg.dev/$PROJECT_ID/gmi/qms-backend:latest
      - --build-arg=GIT_SHA=$COMMIT_SHA
      - --cache-from=europe-west1-docker.pkg.dev/$PROJECT_ID/gmi/qms-backend:latest
      - src/

  # ── 2. Push to Artifact Registry ──────────────────────────────────────────
  - name: gcr.io/cloud-builders/docker
    id: push
    waitFor: [build]
    args:
      - push
      - --all-tags
      - europe-west1-docker.pkg.dev/$PROJECT_ID/gmi/qms-backend

  # ── 3. Deploy to Cloud Run ─────────────────────────────────────────────────
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    waitFor: [push]
    entrypoint: bash
    args:
      - -c
      - |
        gcloud run deploy $_SERVICE \
          --image=europe-west1-docker.pkg.dev/$PROJECT_ID/gmi/qms-backend:$COMMIT_SHA \
          --region=$_REGION \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --concurrency=80 \
          --add-cloudsql-instances=$PROJECT_ID:$_REGION:$_DB_INSTANCE \
          --set-env-vars="DB_USER=gmi,DB_NAME=gmi_qms,DB_HOST=/cloudsql/$PROJECT_ID:$_REGION:$_DB_INSTANCE,DEV_MODE=false,ONELOGIN_SP_ENTITY_ID=https://$_DOMAIN,ONELOGIN_SP_ACS_URL=https://$_DOMAIN/auth/saml/callback" \
          --set-secrets="DB_PASSWORD=db-password:latest,SESSION_SECRET=session-secret:latest,ONELOGIN_IDP_ENTITY_ID=onelogin-idp-entity-id:latest,ONELOGIN_IDP_SSO_URL=onelogin-idp-sso-url:latest,ONELOGIN_IDP_CERT=onelogin-idp-cert:latest" \
          --quiet

images:
  - europe-west1-docker.pkg.dev/$PROJECT_ID/gmi/qms-backend:$COMMIT_SHA
  - europe-west1-docker.pkg.dev/$PROJECT_ID/gmi/qms-backend:latest

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8

timeout: 1200s
